name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      # Generate GitHub Stats Card
      - name: Generate Stats Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: >
            username=${{ github.repository_owner }}
            &show_icons=true
            &include_all_commits=true
            &count_private=true
            &theme=tokyonight
            &hide_border=true
            &disable_animations=false
          path: dist/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Generate Streak Card
      - name: Generate Streak Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: streak
          options: >
            username=${{ github.repository_owner }}
            &theme=tokyonight
            &hide_border=true
          path: dist/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Generate Top Languages Card
      - name: Generate Top Languages Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: >
            username=${{ github.repository_owner }}
            &layout=compact
            &langs_count=8
            &theme=tokyonight
            &hide_border=true
          path: dist/languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Publish generated SVG files
      - name: Deploy to stats-output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: stats-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
